#cloud-config
runcmd:
  - sudo apt update
  - sudo apt install curl git zsh -y
  - chsh -s $(which zsh)
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  - sudo apt update
  - sudo apt upgrade -y